# Generated by Django 4.2.28 on 2026-02-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_goat_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Partial', 'Partial'), ('Paid', 'Paid'), ('Overdue', 'Overdue'), ('Written_Off', 'Written Off')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='goat',
            name='breed',
            field=models.CharField(choices=[('boer', 'Boer'), ('saanen', 'Saanen'), ('alpine', 'Alpine'), ('nubian', 'Nubian'), ('anglo_nubian', 'Anglo-Nubian'), ('toggeneburg', 'Toggeneburg'), ('chamois_colored', 'Chamois Colored'), ('oberhasli', 'Oberhasli'), ('sirohi', 'Sirohi (सिरोही)'), ('barbari', 'Barbari (बरबरी)'), ('jamunapari', 'Jamunapari (जमुनापारी)'), ('beetal', 'Beetal (बीटल)'), ('osmanabadi', 'Osmanabadi (उस्मानाबादी)'), ('marwari', 'Marwari (मारवाड़ी)'), ('kutchi', 'Kutchi (कच्छी)'), ('zalawadi', 'Zalawadi (झालावाड़ी)'), ('ganjam', 'Ganjam (गंजाम)'), ('local', 'Local/Desi (देसी)')], max_length=20),
        ),
    ]
